package Vista;

import Control.Agenda;
import Control.ExistenciaException;
import Control.ExistenciaTextoErrores;
import java.awt.FileDialog;
import java.io.FileNotFoundException;
import java.io.IOException;
import static java.nio.file.Files.list;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collections;
import static java.util.Collections.list;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

/**
 *
 * @author Multi
 */
public class MiVentana extends java.awt.Frame {
    Agenda ag;
    FileDialog dialogoguardar;
    FileDialog dialogorecuperar;
    FileDialog dialogoimportar;
    FileDialog dialogolistarfichero;
    FileDialog dialogoficherocumple;
    Ventanalistados vl;
    VentanaRespuestas vr;
    /**
     * Creates new form MiVentana
     */
    public MiVentana(){
        initComponents(); // Inicializa los componentes gráficos de la ventana
        ag = new Agenda(); // Se crea un objeto de la clase Agenda
        dialogoguardar = new FileDialog(this, "Guardar archivo", FileDialog.SAVE);
        dialogoguardar.setVisible(false);
        dialogorecuperar = new FileDialog (this, "Fichero recuperado", FileDialog.LOAD);
        dialogorecuperar.setVisible(false);
        dialogoimportar = new FileDialog (this, "Fichero Importado", FileDialog.LOAD);
        dialogoimportar.setVisible(false);
        dialogolistarfichero = new FileDialog (this,"Fichero Listado", FileDialog.SAVE);
        dialogolistarfichero.setVisible(false);
        dialogoficherocumple = new FileDialog(this,"Fichero Listado Por Cumpleañios", FileDialog.SAVE);
        dialogoficherocumple.setVisible(false);
        vl = new Ventanalistados(this, true);
        vl.setVisible(false);
        vr = new VentanaRespuestas(this, true);
        vr.setVisible(false);
        setLocation(350,150);
        //setSize(650, 550);
        setTitle("Agenda de Contactos");

    //try {
           /* ag.recuperar("C:\\Programacion\\MisFicheros\\nuevo.ser"); // Recupera los datos de un archivo*/
            rellenar_lista(); // Llena la lista de contactos con los datos recuperados
        /*} catch (IOException ex) {
            vl.SetContenido(ex.toString());
            vl.setVisible(true);
        } catch (ClassNotFoundException ex) {
            vl.SetContenido(ex.toString());            
            vl.setVisible(true);
        }*/
            TextNombre.setText("");
            textTelefono.setText("");
            textOpcion.setText("");
            labelOpcion.setText("");
            contactos.setText("Agenda de Contactos"); // Borra el texto de la etiqueta de contactos
            butalta.setEnabled(false); // Desactiva el botón "Alta"
            bbaja.setEnabled(false); // Desactiva el botón "Borrar"
            bmodificar.setEnabled(false); // Desactiva el botón "Modificar"       
    }
    
    private void rellenar_lista(){
        listaContactos.removeAll();// Borra todos los elementos de la lista
        ArrayList<String>nombre=ag.getNombre();// Obtiene la lista de nombres desde la agenda
        listaContactos.add("<Nuevo Contacto>");// Agrega la opción de nuevo contacto
        for(String n: nombre){
        listaContactos.add(n);}// Agrega cada nombre de contacto a la lista
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        balta = new java.awt.Button();
        canvas1 = new java.awt.Canvas();
        checkbox2 = new java.awt.Checkbox();
        checkbox1 = new java.awt.Checkbox();
        checkbox4 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        panelSur = new java.awt.Panel();
        butalta = new java.awt.Button();
        bbaja = new java.awt.Button();
        bmodificar = new java.awt.Button();
        panelCentral = new java.awt.Panel();
        pizquierdo = new java.awt.Panel();
        panel7 = new java.awt.Panel();
        contactos = new java.awt.Label();
        listaContactos = new java.awt.List();
        panel2 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        pderecho = new java.awt.Panel();
        panel5 = new java.awt.Panel();
        panelDerecho = new java.awt.Panel();
        checkboxAmigo = new java.awt.Checkbox();
        checkboxProfesional = new java.awt.Checkbox();
        panel6 = new java.awt.Panel();
        panelDatos = new java.awt.Panel();
        labelNombre = new java.awt.Label();
        TextNombre = new java.awt.TextField();
        labelTelefono = new java.awt.Label();
        textTelefono = new java.awt.TextField();
        labelOpcion = new java.awt.Label();
        textOpcion = new java.awt.TextField();
        panel8 = new java.awt.Panel();
        menuBar1 = new java.awt.MenuBar();
        Archivos = new java.awt.Menu();
        Guardar = new java.awt.MenuItem();
        Recuperar = new java.awt.MenuItem();
        Importar = new java.awt.MenuItem();
        Listados = new java.awt.Menu();
        ListaAlfabetica = new java.awt.Menu();
        Pantallaalfa = new java.awt.MenuItem();
        Ficheroalfa = new java.awt.MenuItem();
        ListadoCumpleanios = new java.awt.Menu();
        Pantallacumple = new java.awt.MenuItem();
        Ficherocumple = new java.awt.MenuItem();

        balta.setBackground(new java.awt.Color(51, 51, 255));
        balta.setForeground(new java.awt.Color(255, 255, 255));

        checkbox2.setLabel("Profesional");

        checkbox1.setLabel("Amigo");

        checkbox4.setLabel("checkbox4");

        checkbox3.setLabel("checkbox3");

        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setSize(new java.awt.Dimension(660, 550));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new java.awt.BorderLayout(25, 0));

        panelSur.setBackground(new java.awt.Color(240, 248, 255));
        panelSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15));

        butalta.setActionCommand("Alta");
        butalta.setBackground(new java.awt.Color(51, 102, 255));
        butalta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        butalta.setForeground(new java.awt.Color(255, 255, 255));
        butalta.setLabel("Añadir");
        butalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaltaActionPerformed(evt);
            }
        });
        panelSur.add(butalta);
        butalta.getAccessibleContext().setAccessibleDescription("");

        bbaja.setActionCommand("Borrar");
        bbaja.setBackground(new java.awt.Color(51, 102, 255));
        bbaja.setForeground(new java.awt.Color(255, 255, 255));
        bbaja.setLabel("Eliminar");
        bbaja.setName(""); // NOI18N
        bbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbajaActionPerformed(evt);
            }
        });
        panelSur.add(bbaja);

        bmodificar.setBackground(new java.awt.Color(51, 102, 255));
        bmodificar.setForeground(new java.awt.Color(255, 255, 255));
        bmodificar.setLabel("Editar");
        bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificarActionPerformed(evt);
            }
        });
        panelSur.add(bmodificar);

        add(panelSur, java.awt.BorderLayout.SOUTH);

        panelCentral.setLayout(new java.awt.GridLayout(1, 2));

        pizquierdo.setBackground(new java.awt.Color(240, 248, 255));
        pizquierdo.setLayout(new java.awt.BorderLayout(20, 0));

        panel7.setBackground(new java.awt.Color(240, 248, 255));
        panel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        contactos.setAlignment(java.awt.Label.CENTER);
        contactos.setBackground(new java.awt.Color(240, 248, 255));
        contactos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contactos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contactos.setName(""); // NOI18N
        contactos.setPreferredSize(new java.awt.Dimension(250, 40));
        contactos.setText("Agenda de Contactos");
        panel7.add(contactos);
        contactos.getAccessibleContext().setAccessibleName("label");

        pizquierdo.add(panel7, java.awt.BorderLayout.NORTH);

        listaContactos.setName(""); // NOI18N
        listaContactos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaContactosItemStateChanged(evt);
            }
        });
        pizquierdo.add(listaContactos, java.awt.BorderLayout.CENTER);

        panel2.setBackground(new java.awt.Color(240, 248, 255));
        panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pizquierdo.add(panel2, java.awt.BorderLayout.WEST);

        panel3.setBackground(new java.awt.Color(240, 248, 255));
        pizquierdo.add(panel3, java.awt.BorderLayout.EAST);

        panel4.setBackground(new java.awt.Color(240, 248, 255));
        pizquierdo.add(panel4, java.awt.BorderLayout.SOUTH);

        panelCentral.add(pizquierdo);

        pderecho.setBackground(new java.awt.Color(102, 255, 204));
        pderecho.setLayout(new java.awt.BorderLayout());

        panel5.setBackground(new java.awt.Color(240, 248, 255));
        panel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 50));

        panelDerecho.setLayout(new java.awt.GridLayout(1, 2));
        panel5.add(panelDerecho);

        checkboxAmigo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkboxAmigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkboxAmigo.setLabel("Amigo");
        checkboxAmigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxAmigoItemStateChanged(evt);
            }
        });
        panel5.add(checkboxAmigo);

        checkboxProfesional.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkboxProfesional.setLabel("Profesional");
        checkboxProfesional.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxProfesionalItemStateChanged(evt);
            }
        });
        panel5.add(checkboxProfesional);

        pderecho.add(panel5, java.awt.BorderLayout.NORTH);

        panel6.setBackground(new java.awt.Color(153, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        panel6.setLayout(flowLayout1);
        pderecho.add(panel6, java.awt.BorderLayout.EAST);

        panelDatos.setBackground(new java.awt.Color(240, 248, 255));
        panelDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelDatos.setMaximumSize(new java.awt.Dimension(350, 350));
        panelDatos.setPreferredSize(new java.awt.Dimension(260, 226));
        panelDatos.setLayout(new java.awt.GridBagLayout());

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombre.setPreferredSize(new java.awt.Dimension(110, 24));
        labelNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 11);
        panelDatos.add(labelNombre, gridBagConstraints);

        TextNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        TextNombre.setText("nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 11, 10, 11);
        panelDatos.add(TextNombre, gridBagConstraints);

        labelTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTelefono.setPreferredSize(new java.awt.Dimension(110, 24));
        labelTelefono.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        panelDatos.add(labelTelefono, gridBagConstraints);

        textTelefono.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textTelefono.setText("teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 11, 10, 11);
        panelDatos.add(textTelefono, gridBagConstraints);

        labelOpcion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelOpcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelOpcion.setPreferredSize(new java.awt.Dimension(110, 24));
        labelOpcion.setText("Opciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(8, 9, 8, 9);
        panelDatos.add(labelOpcion, gridBagConstraints);

        textOpcion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textOpcion.setText("empresa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 11, 10, 11);
        panelDatos.add(textOpcion, gridBagConstraints);

        pderecho.add(panelDatos, java.awt.BorderLayout.CENTER);
        panelDatos.getAccessibleContext().setAccessibleName("");

        panel8.setBackground(new java.awt.Color(240, 248, 255));
        panel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel8.setName(""); // NOI18N
        panel8.setPreferredSize(new java.awt.Dimension(20, 20));
        panel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 20));
        pderecho.add(panel8, java.awt.BorderLayout.EAST);

        panelCentral.add(pderecho);

        add(panelCentral, java.awt.BorderLayout.CENTER);

        Archivos.setLabel("Archivos");

        Guardar.setLabel("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Archivos.add(Guardar);

        Recuperar.setLabel("Recuperar");
        Recuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecuperarActionPerformed(evt);
            }
        });
        Archivos.add(Recuperar);

        Importar.setLabel("Importar");
        Importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarActionPerformed(evt);
            }
        });
        Archivos.add(Importar);

        menuBar1.add(Archivos);

        Listados.setLabel("Listados");

        ListaAlfabetica.setLabel("Listado Alfabetico");
        ListaAlfabetica.setName("");

        Pantallaalfa.setLabel("Pantalla");
        Pantallaalfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaalfaActionPerformed(evt);
            }
        });
        ListaAlfabetica.add(Pantallaalfa);

        Ficheroalfa.setLabel("Fichero");
        Ficheroalfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FicheroalfaActionPerformed(evt);
            }
        });
        ListaAlfabetica.add(Ficheroalfa);

        Listados.add(ListaAlfabetica);

        ListadoCumpleanios.setLabel("Listado Cumpleanios");

        Pantallacumple.setLabel("Pantalla");
        Pantallacumple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallacumpleActionPerformed(evt);
            }
        });
        ListadoCumpleanios.add(Pantallacumple);

        Ficherocumple.setLabel("Fichero");
        Ficherocumple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FicherocumpleActionPerformed(evt);
            }
        });
        ListadoCumpleanios.add(Ficherocumple);

        Listados.add(ListadoCumpleanios);

        menuBar1.add(Listados);

        setMenuBar(menuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        vr.setContenido("¿Estás seguro de querer salir?");
        vr.setVisible(true);
        boolean a=vr.getRespuesta();
        if(a) {
        System.exit(0);
        }
    }//GEN-LAST:event_exitForm

    private void listaContactosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaContactosItemStateChanged
        // TODO add your handling code here:                                              
            String n = listaContactos.getSelectedItem(); // Obtiene el contacto seleccionado
            if ("<Nuevo Contacto>".equals(n)) {
                // Prepara la interfaz para añadir un nuevo contacto
                checkboxAmigo.setState(false);
                checkboxProfesional.setState(false);
                checkboxAmigo.setEnabled(true);
                checkboxProfesional.setEnabled(true);
                TextNombre.setEnabled(true);
                TextNombre.setText("");
                textTelefono.setEnabled(true);
                textTelefono.setText("");
                textOpcion.setEnabled(true);
                textOpcion.setText("");
                labelOpcion.setText("Opciones");
                butalta.setEnabled(true);
                bbaja.setEnabled(false);
                bmodificar.setEnabled(false);
            }else {
                // Carga los datos del contacto seleccionado
            ArrayList<String> datos = ag.dameContacto(n);

            System.out.println("Contacto: " + n);
            System.out.println("Datos: " + datos);

            if (datos == null || datos.size() < 3) {
                return;
            }

            TextNombre.setText(datos.get(1));
            textTelefono.setText(datos.get(2));

            if (datos.get(0).equals("A")) { 
                checkboxAmigo.setState(true);
                checkboxProfesional.setState(false);
                textOpcion.setText(datos.get(3));
                labelOpcion.setText("Fecha de cumpleaños");
            } else if (datos.get(0).equals("P")) { 
                checkboxProfesional.setState(true);
                checkboxAmigo.setState(false);
                textOpcion.setText(datos.get(4));
                labelOpcion.setText("Empresa"); 
            }
                butalta.setEnabled(false);
                bbaja.setEnabled(true);
                bmodificar.setEnabled(true);
                checkboxAmigo.setEnabled(false);
                checkboxProfesional.setEnabled(false);
           }
                //pack();
    }//GEN-LAST:event_listaContactosItemStateChanged

    private void checkboxAmigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxAmigoItemStateChanged
        // TODO add your handling code here:
        boolean estadoamigo=checkboxAmigo.getState();
        checkboxProfesional.setState( !estadoamigo );
        if(estadoamigo)
            labelOpcion.setText("Fecha de cumpleaños");
        else 
            labelOpcion.setText("Empresa");
        //pack();
    }//GEN-LAST:event_checkboxAmigoItemStateChanged

    private void checkboxProfesionalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxProfesionalItemStateChanged
        // TODO add your handling code here:
        boolean estadopro=checkboxProfesional.getState();
        checkboxAmigo.setState(!estadopro);
        if(estadopro)
            labelOpcion.setText("Empresa");
        else
            labelOpcion.setText("Fecha de cumpleaños");
        //pack();
        
    }//GEN-LAST:event_checkboxProfesionalItemStateChanged

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        dialogoguardar.setVisible(true);
        String ruta=dialogoguardar.getDirectory()+"\\"+dialogoguardar.getFile();
        if(!ruta.contains("null")){
        try {
            ag.salvar(ruta);
            } catch (IOException ex) {
               vl.SetContenido(ex.toString());            
               vl.setVisible(true);
            }
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void RecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecuperarActionPerformed
       /* // TODO add your handling code here:
        dialogorecuperar.setVisible(true);
        String ruta = dialogorecuperar.getDirectory() + "\\" + dialogorecuperar.getFile();
        if(!ruta.contains("null")){
        try {
            ag.recuperar(ruta);
            rellenar_lista();
        } catch (IOException ex) {
           vl.SetContenido(ex.toString());            
           vl.setVisible(true);
        } catch (ClassNotFoundException ex) {
           vl.SetContenido(ex.toString());            
           vl.setVisible(true);
        }
        }*/
    }//GEN-LAST:event_RecuperarActionPerformed

    private void ImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarActionPerformed
        // TODO add your handling code here:
        dialogoimportar.setVisible(true);
        String ruta = dialogoimportar.getDirectory() + "\\" + dialogoimportar.getFile();
        if(!ruta.contains("null")){
        try {
            ag.importar(ruta);
            rellenar_lista();
        } catch (IOException ex) {
           vl.SetContenido(ex.toString());            
           vl.setVisible(true);
        } catch (ExistenciaTextoErrores ex) {
           vl.SetContenido(ex.toString());            
           vl.setVisible(true);
        } catch (ParseException ex) {
           vl.SetContenido(ex.toString());            
           vl.setVisible(true);
        } catch (ExistenciaException ex) {
           vl.SetContenido(ex.toString());            
           vl.setVisible(true);
        } catch (SQLException ex) {
           vl.SetContenido(ex.toString());            
           vl.setVisible(true);
            }
        }
    }//GEN-LAST:event_ImportarActionPerformed

    private void FicheroalfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FicheroalfaActionPerformed
        // TODO add your handling code here:
        dialogolistarfichero.setVisible(true);
        String ruta = dialogolistarfichero.getDirectory() + "\\" + dialogolistarfichero.getFile();
        if(!ruta.contains("null")){
        try {
            ag.listarEnFichero(ruta);
        } catch (Exception ex) {
            vl.SetContenido(ex.toString());
            vl.setVisible(true);
        }
        }
    }//GEN-LAST:event_FicheroalfaActionPerformed

    private void FicherocumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FicherocumpleActionPerformed
        // TODO add your handling code here:
        dialogoficherocumple.setVisible(true);
        String ruta = dialogoficherocumple.getDirectory() + "\\" + dialogoficherocumple.getFile();
        if(!ruta.contains("null")){
        try {
            ag.listaCumplaniosEnFichero(ruta);
        } catch (Exception ex) {
            vl.SetContenido(ex.toString());
            vl.setVisible(true);
        }
        }
    }//GEN-LAST:event_FicherocumpleActionPerformed

    private void PantallaalfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaalfaActionPerformed
        // TODO add your handling code here:
        String cadena="";
        try {
            cadena = ag.listar();
        } catch (Exception ex) {
            cadena=ex.toString();
        }
        vl.SetContenido(cadena);
        vl.setVisible(true);
    }//GEN-LAST:event_PantallaalfaActionPerformed

    private void PantallacumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallacumpleActionPerformed
        // TODO add your handling code here:
        String cadena="";
        try {
            cadena=ag.listaCumpleanios();
        } catch (Exception ex) {
            cadena=ex.toString();
        }
        vl.SetContenido(cadena);
        vl.setVisible(true);
    }//GEN-LAST:event_PantallacumpleActionPerformed

    private void bmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificarActionPerformed
        // TODO add your handling code here:
        String nombre = TextNombre.getText();
        String nuevoTelefono = textTelefono.getText();
        String nuevaEmpresa = textOpcion.getText();
        String nuevaFecha = textOpcion.getText();

        try {
            ag.modificar(nombre, nuevoTelefono, nuevaEmpresa, nuevaFecha);
            JOptionPane.showMessageDialog(
                this,
                "Contacto modificado correctamente",
                "Modificación realizada",
                JOptionPane.INFORMATION_MESSAGE
            );
        } catch (ParseException ex) {
            vl.SetContenido("Fecha erronea." + ex.toString());
            vl.setVisible(true);
        } catch (ExistenciaException ex) {
            vl.SetContenido(ex.toString());
            vl.setVisible(true);
        } catch (NumberFormatException ex) {
            vl.SetContenido("Numero erroneo." + ex.toString());
            vl.setVisible(true);
        }
    }//GEN-LAST:event_bmodificarActionPerformed

    private void bbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbajaActionPerformed
        // TODO add your handling code here:
        String n=TextNombre.getText(); // Obtiene el nombre del contacto
        vr.setContenido("¿Estás seguro de borrar a " + n + "?");
        vr.setVisible(true);
        boolean a=vr.getRespuesta();
        if(a) {
            try {
                ag.borrar(n); // Borra el contacto de la agenda           
                rellenar_lista(); // Actualiza la lista
                JOptionPane.showMessageDialog(
                    this,
                    "Contacto eliminado correctamente",
                    "Contacto eliminado",
                    JOptionPane.INFORMATION_MESSAGE
                ); 
                bbaja.setEnabled(false); // Desactiva el botón "Borrar"
                TextNombre.setText("");
                textTelefono.setText("");
                textOpcion.setText("");

            } catch (ExistenciaException ex) {
                vl.SetContenido(ex.toString());
                vl.setVisible(true);
            }
        }
    }//GEN-LAST:event_bbajaActionPerformed

    private void butaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaltaActionPerformed
        // TODO add your handling code here:
        String nombre = TextNombre.getText();
        String telefono = textTelefono.getText();
        String empresa = textOpcion.getText();
        String fn = textOpcion.getText();
        String tipo;
        if(checkboxAmigo.getState()){
            tipo="Amigo";
        } else
        tipo="Profesional";
        try {
            ag.alta(nombre, telefono, fn, empresa, tipo);
            rellenar_lista();
                JOptionPane.showMessageDialog(
                    this,
                    "Contacto añadido correctamente",
                    "Contacto añadido",
                    JOptionPane.INFORMATION_MESSAGE
                ); 
        } catch (NumberFormatException ex){
            vl.SetContenido("Numero erroneo. \n" + ex.toString());
            vl.setVisible(true);
        } catch (ParseException ex) {
            vl.SetContenido("Fecha erronea. \n" + ex.toString());
            vl.setVisible(true);
        } catch (ExistenciaException ex) {
            vl.SetContenido(ex.toString());
            vl.setVisible(true);
        } catch (IllegalArgumentException ex) {
            vl.SetContenido("Otros errores de datos." + ex.toString());
            vl.setVisible(true);
        } catch (SQLException ex) {
            vl.SetContenido("Texto del nombre demasiado largo.");
            vl.setVisible(true);
        }
    }//GEN-LAST:event_butaltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                    new MiVentana().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Menu Archivos;
    private java.awt.MenuItem Ficheroalfa;
    private java.awt.MenuItem Ficherocumple;
    private java.awt.MenuItem Guardar;
    private java.awt.MenuItem Importar;
    private java.awt.Menu ListaAlfabetica;
    private java.awt.Menu ListadoCumpleanios;
    private java.awt.Menu Listados;
    private java.awt.MenuItem Pantallaalfa;
    private java.awt.MenuItem Pantallacumple;
    private java.awt.MenuItem Recuperar;
    private java.awt.TextField TextNombre;
    private java.awt.Button balta;
    private java.awt.Button bbaja;
    private java.awt.Button bmodificar;
    private java.awt.Button butalta;
    private java.awt.Canvas canvas1;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private java.awt.Checkbox checkbox4;
    private java.awt.Checkbox checkboxAmigo;
    private java.awt.Checkbox checkboxProfesional;
    private java.awt.Label contactos;
    private java.awt.Label labelNombre;
    private java.awt.Label labelOpcion;
    private java.awt.Label labelTelefono;
    private java.awt.List listaContactos;
    private java.awt.MenuBar menuBar1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private java.awt.Panel panel7;
    private java.awt.Panel panel8;
    private java.awt.Panel panelCentral;
    private java.awt.Panel panelDatos;
    private java.awt.Panel panelDerecho;
    private java.awt.Panel panelSur;
    private java.awt.Panel pderecho;
    private java.awt.Panel pizquierdo;
    private java.awt.TextField textOpcion;
    private java.awt.TextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
