/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package Vista;

/**
 *
 * @author Multi
 */
public class VentanaRespuestas extends java.awt.Dialog {
        VentanaRespuestas vr;
        boolean respuesta;
    /**
     * Creates new form VentanaRespuestas
     */
    public VentanaRespuestas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation(400,200);
        
    }
    
    public void setContenido (String str){
        label1.setText(str);
        pack();
    }
    
    public boolean getRespuesta(){
        return respuesta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        buttonSI = new java.awt.Button();
        buttonNO = new java.awt.Button();
        label1 = new java.awt.Label();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        buttonSI.setLabel("SI");
        buttonSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSIActionPerformed(evt);
            }
        });
        panel1.add(buttonSI);

        buttonNO.setLabel("NO");
        buttonNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNOActionPerformed(evt);
            }
        });
        panel1.add(buttonNO);

        add(panel1, java.awt.BorderLayout.SOUTH);

        label1.setText("label1");
        add(label1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        //setVisible(false);
        //dispose();
    }//GEN-LAST:event_closeDialog

    private void buttonSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSIActionPerformed
        // TODO add your handling code here:
        respuesta=true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonSIActionPerformed

    private void buttonNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNOActionPerformed
        // TODO add your handling code here:
        respuesta=false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonNOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaRespuestas dialog = new VentanaRespuestas(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonNO;
    private java.awt.Button buttonSI;
    private java.awt.Label label1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

}
